main/urls.py
from django.urls import path
from main.views import show_main
from main.views import show_main, create_product
from main.views import show_main, create_product, show_xml 
from main.views import show_main, create_product, show_xml, show_json
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id 
from main.views import register #sesuaikan dengan nama fungsi yang dibuat
from main.views import login_user #sesuaikan dengan nama fungsi yang dibuat
from main.views import logout_user
from main.views import edit_product
from main.views import delete_product
from main.views import get_product_json
from main.views import add_product_ajax, create_product_flutter


app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete/<int:id>', delete_product, name='delete_product'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
] 

wahyus_shop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    price = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "amount", "price"]

main/views.py
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.forms import ProductForm
from django.urls import reverse
from main.models import Product
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json

@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'class': 'PBP E',
        'products': products,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)
    

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def get_product_json(request):
    product_item = Product.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get data berdasarkan ID
    product = Product.objects.get(pk = id)
    # Hapus data
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        description = request.POST.get("description")
        amount = request.POST.get("amount")
        price = request.POST.get("price")
        user = request.user

        new_product = Product(name=name, description=description, amount=amount, user=user, price=price)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

main/templates/create_product.html
{% extends 'base.html' %} 

{% block meta %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add New Product</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            margin: 20px; 
        }
    </style>
</head>
{% endblock meta %}

{% block content %}
<body style="background-color: #f0f0f0;">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-header bg-primary text-white">
                        <h1 class="card-title">Add New Product</h1>
                    </div>

                    <div class="card-body"></div>
                        <form method="POST">
                            {% csrf_token %}
                            <table style="margin: 20px;">
                                {{ form.as_table }}
                                <tr>
                                    <td></td>
                                    <td>
                                        <input class="btn btn-danger" type="submit" value="Add Product">
                                    </td>
                                </tr>
                            </table>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
{% endblock meta %}

{% block content %}

<body>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-header text-white" style="background-color: #66A182;">
                    <h1 class="card-title">Login</h1>
                </div>

                <div class="card-body">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="form-group py-2">
                            <label for="username">Username:</label>
                            <input type="text" name="username" id="username" placeholder="Username" class="form-control">
                        </div>
                        <div class="form-group py-2">
                            <label for="password">Password:</label>
                            <input type="password" name="password" id="password" placeholder="Password" class="form-control">
                        </div>
                        <div class="form-group py-2">
                            <button class="btn btn-primary btn-block" style="background-color: #66A182; border: none;" type="submit">Login</button>
                        </div>
                    </form>

                    {% if messages %}
                        <div class="alert alert-danger">
                            <ul>
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    
                    <p class="text-center mb-0">Don't have an account yet? <a href="{% url 'main:register' %}" class="text-primary">Register Now</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}

<style>
    body {
        background: linear-gradient(to bottom, #CAFFB9, #CAFFB9); /* Set the background color for the entire page */
    }
</style>
<!-- As a link -->
<nav class="navbar navbar-expand-lg bg-transparent-white">
    <div class="container-fluid">
      <a class="navbar-brand" href="#" style="color: black; margin-left: 45px;font-weight: bold;">Wahyus Shop Page</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            
              <a href="{% url 'main:logout' %}" class="ml-2">
                <button class="btn btn-danger" style="background-color: #2E4057; border: none; margin-right: 45px;">Logout</button>
            </a>
            
            </button>
          </li>
        </ul>
      </div>
    </div>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</nav>

<style>


    .bg-transparent-white {
        background-color: rgba(255, 255, 255, 0.7); /* Adjust the last value (0.7) for transparency */
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        border: 1px solid #dddddd;
        padding: 12px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:nth-child(even) {
        background-color: #f5f5f5; /* Alternate row color */
    }

    tr:nth-child(odd) {
        background-color: #e0e0e0; /* Alternate row color */
    }
</style>
  
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="card" style="background-color: #66A182; border-radius: 15px;">
                <div class="card-body">
                    <h5 class="card-title" style="font-size: 42px;">Hi, {{name}}!</h5>
                    <h5 class="card-title">Name: {{name}}</h5>
                    <h5 class="card-title">Class: {{class}}</h5>
                </div>
            </div>
            <br />
        </div>
    </div>
    
    <div class="row mt-4">
        <div class="col-md-12">            
            
            <div id="product_table"></div>
            
            
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form id="form" onsubmit="return false;">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <label for="name" class="col-form-label">Name:</label>
                                    <input type="text" class="form-control" id="name" name="name"></input>
                                </div>
                                <div class="mb-3">
                                    <label for="description" class="col-form-label">Description:</label>
                                    <textarea class="form-control" id="description" name="description"></textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="amount" class="col-form-label">Amount:</label>
                                    <input type="number" class="form-control" id="amount" name="amount"></input>
                                </div>
                                <div class="mb-3">
                                    <label for="price" class="col-form-label">Price:</label>
                                    <input type="number" class="form-control" id="price" name="price"></input>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary" style="background-color: #66A182; border: none;" id="button_add" data-bs-dismiss="modal">Add Product</button>
                        </div>
                    </div>
                </div>            </div>
    
                <div class="text-right">
                    <h5 style="display: inline-block; margin-right: 420px; margin-top: 10px;">Last Login Session: {{ last_login }}</h5>
                    <button type="button" class="btn btn-primary" style="background-color: #66A182; border: none;" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>
                    <a href="{% url 'main:logout' %}" class="ml-2">
                        <button class="btn btn-danger" style="background-color: #2E4057; border: none;">Logout</button>
                    </a>
                    
                </div> 
                <br />
            </div>
        </div>    
    </div>
</div>


<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }

    async function refreshProducts() {
        document.getElementById("product_table").innerHTML = ""
        const products = await getProducts()
        let htmlString = `
            <div class="row">
                {% for product in products %}
                <div class="col-md-4 mb-4">
                    <div class="card bg-transparent-white" style="border-radius: 15px;">
                        <div id="product_table" class="card-body">
                            <h5 class="card-text text-center">{{ product.name }}</h5>
                            <p class="card-text">Description: {{ product.description }}</p>
                            <p class="card-text">Amount: {{ product.amount }}</p>
                            <p class="card-text">Price: {{ product.price }}</p>
                            
                            <a href="{% url 'main:delete_product' product.pk %}">
                                <button class="btn btn-primary" style="background-color: #66A182; border: none; border-radius: 5px;">
                                    Delete
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>\n`;
        
        document.getElementById("product_table").innerHTML = htmlString
        
    }

    refreshProducts()

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }

    document.getElementById("button_add").onclick = addProduct
</script>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>{% endblock meta %}

{% block content %}  
<body>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-white" style="background-color: #66A182; ">
                    <h1 class="card-title">Register</h1>
                </div>

                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }} <!-- Menggunakan as_p untuk menampilkan input sebagai paragraf -->

                        <div class="form-group text-center">
                            <button class="btn btn-primary" style="background-color: #66A182; border: none;" type="submit" name="submit">Daftar</button>
                        </div>
                    </form>

                    {% if messages %}
                        <div class="alert alert-danger">
                            <ul>
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>

{% endblock content %}